version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_HOST: 'http://localhost:8080/api'
    environment:
      PORT: 80
    depends_on:
      - api
    ports:
      - '80:80' # Экспонируем порт 80 из контейнера на порт 80 на хосте
    networks:
      - app-network

  api:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./backend/:/usr/src/api
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: incidents
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge