apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yaml -o app/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yaml -o app/
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
          - name: PORT
            value: "80"
          image: cr.yandex/crp1eos7geaq6pnfkbv2/frontend:latest
          name: frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
