apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yaml -o app/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yaml -o app/
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
          - name: POSTGRES_DB
            value: incidents
          - name: POSTGRES_PASSWORD
            value: postgresql
          - name: POSTGRES_USER
            value: postgresql
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          image: postgres:latest
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-cm1
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - configMap:
            name: postgres-cm1
          name: postgres-cm1
